### ISSUE TITLE
The mod exists.

### ISSUE THREAD

**Issue by HyperInvox** [NotSomeoneElse/Cloudburst#1]
See title. 
This mod was a testament to all the failings of the modding community, its revival is against God's will and is an insult to the natural order.

Also you left my lore log for Jape's Cloak in the game, but honestly I don't care cause it's dogshit and my name isn't attached to it, so it's only making you look worse.
P.S. the new wyatt design looks like ass and is barely different from my design. i literally said that i wouldn't settle for a recolor, how fucking quaint.

**Comment by nayDPz** [comment]
euthanasia would be a mercy

**Comment by Nebby1999** [comment]
Sounds like someone is coping from being kicked due to bigotry and being banned from the main modcord :3c

**Comment by urbanawakening** [comment]
![ltg](https://github.com/NotSomeoneElse/Cloudburst/assets/49351666/8ed33840-26df-40f7-94cc-87795f06dbb9)

**Comment by JaceDaDorito** [comment]
sucks to suck

**Comment by NotSomeoneElse** [comment]
This is why nobody likes you

**Comment by Nebby1999** [comment]
![image](https://github.com/NotSomeoneElse/Cloudburst/assets/78170922/2081166a-2c19-4f88-a0dd-702aceb21097)

**Comment by Dotflare** [comment]
WAAAAA WAAAA CRYY SOME MOREEE
