### ISSUE TITLE
Custodian Umbra jingle keeps playing after death

### ISSUE THREAD

**Issue by Phreelosu** [NotSomeoneElse/Cloudburst#8]
yea cant really provide a log as it consistently happens without errors

Umbra of Custodian once uses his utility, and dies while jingle is playing, it keeps playing even after switching scenes, and can be heard subtly even in main menu after run end too

**Comment by Phreelosu** [comment]
installing Goorakh's https://thunderstore.io/package/Goorakh/LoopingSoundFix/ fixes this issue
but it might not be wise to entirely depend on this package, so while this does the job, I'll keep this open

**Comment by TheTimeSweeper** [comment]
wow dec 28 😬 
he's had an update in the works that I think was looking into this. I'll take a look

**Comment by Phreelosu** [comment]
this isn't happening anymore in latest versions, at least I cant reproduce it now so yea
